DROP DATABASE IF EXISTS T5_juego;
CREATE DATABASE T5_juego;
USE T5_juego;

CREATE TABLE JUGADOR (
	USUARIO VARCHAR(20) NOT NULL,
	CONTRASENA VARCHAR(30),
	PARTIDASGANADAS INT,
	PARTIDASJUGADAS INT,
	PRIMARY KEY (USUARIO)
)ENGINE=InnoDB;

CREATE TABLE PARTIDAS (
	ID INTEGER NOT NULL ,
	USUARIO_G VARCHAR(20) ,
	DURACION INT,
	MEJORJUGADA INT,
	FECHA VARCHAR(20),
	HORA VARCHAR(10),
	FOREIGN KEY (USUARIO_G) REFERENCES JUGADOR(USUARIO),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

INSERT INTO JUGADOR VALUES ('INGRID','AAA',15,25);
INSERT INTO JUGADOR VALUES ('ALEIX','BBB',7,14);
INSERT INTO JUGADOR VALUES ('DANI','CCC',5,9);

INSERT INTO PARTIDAS VALUES (1,'ALEIX',14,3,'11-03-2021','10:30');
INSERT INTO PARTIDAS VALUES (2,'DANI',16,4,'10-03-2021','14:30');
INSERT INTO PARTIDAS VALUES (3,'INGRID',13,5,'09-03-2021','11:30');
